name: CD

on:
  release:
    types: [created]

jobs:
  build:
    name: ${{ matrix.MAXICONDA_NAME }}-${{ matrix.OS_NAME }}-${{ matrix.ARCH }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            ARCH: x86_64
            MAXICONDA_NAME: "maxiconda"
            OS_NAME: "Windows"

          - os: macos-latest
            ARCH: x86_64
            MAXICONDA_NAME: "maxiconda"
            OS_NAME: "MacOS"

          - os: macos-latest
            ARCH: arm64
            MAXICONDA_NAME: "maxiconda"
            OS_NAME: "MacOS"

          - os: ubuntu-latest
            ARCH: x86_64
            DOCKER_ARCH: amd64
            DOCKERIMAGE: condaforge/linux-anvil-comp7
            MAXICONDA_NAME: "maxiconda"
            OS_NAME: "Linux"

          - os: ubuntu-latest
            ARCH: aarch64
            DOCKER_ARCH: arm64v8
            DOCKERIMAGE: condaforge/linux-anvil-aarch64
            MAXICONDA_NAME: "maxiconda"
            OS_NAME: "Linux"

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Windows-only setup
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
      if: contains(matrix.OS_NAME, 'Windows')

    - name: Build and test maxiconda
      env:
        ARCH: ${{ matrix.ARCH }}
        MAXICONDA_NAME: ${{ matrix.MAXICONDA_NAME }}
        OS_NAME: ${{ matrix.OS_NAME }}
        DOCKERIMAGE: ${{ matrix.DOCKERIMAGE }}
        DOCKER_ARCH: ${{ matrix.DOCKER_ARCH }}
      run: |
        export MAXICONDA_VERSION=${GITHUB_REF##*/};
        if [[ "$OS_NAME" == "Linux" ]]; then
          bash build_maxiconda_linux.sh;
        fi
        if [[ "$OS_NAME" == "MacOS" ]]; then
          bash build_maxiconda_macos.sh;
        fi
        if [[ "$OS_NAME" == "Windows" ]]; then
          source /c/Miniconda3/Scripts/activate;
          source build_maxiconda_windows.sh;
          cp build/$MAXICONDA_NAME-*-$OS_NAME-$ARCH.$EXT build/$MAXICONDA_NAME.$EXT
        fi
      shell: bash

    - name: Upload release assets
      uses: alexellis/upload-assets@0.2.3
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["build/maxiconda*"]'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies

    - name: Install Jinja2
      run: |
        pip install Jinja2

    - name: Add maxiconda proxy for Linux/MacOS
      run: |
        mkdir build
        export RELEASE_VERSION=${GITHUB_REF##*/}
        python scripts/tag_script.py
        cp maxiconda.sh build/

    - name: Upload release assets
      uses: alexellis/upload-assets@0.2.3
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["build/maxiconda*"]'
