name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.MAXIFORGE_NAME }}-${{ matrix.OS_NAME }}-${{ matrix.ARCH }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            ARCH: x86_64
            MAXIFORGE_NAME: "maxiforge"
            OS_NAME: "Windows"

          # - os: macos-latest
          #   ARCH: arm64
          #   MAXIFORGE_NAME: "maxiforge"
          #   OS_NAME: "MacOSX"

          # - os: macos-latest
          #   ARCH: x86_64
          #   MAXIFORGE_NAME: "maxiforge-pypy"
          #   OS_NAME: "MacOSX"

          # - os: macos-latest
          #   ARCH: arm64
          #   MAXIFORGE_NAME: "maxiforge-pypy"
          #   OS_NAME: "MacOSX"

          # - os: macos-latest
          #   ARCH: x86_64
          #   MAXIFORGE_NAME: "maxiforge"
          #   OS_NAME: "MacOSX"

          - os: ubuntu-latest
            ARCH: aarch64
            DOCKER_ARCH: arm64v8
            DOCKERIMAGE: condaforge/linux-anvil-aarch64
            MAXIFORGE_NAME: "maxiforge"
            OS_NAME: "Linux"

          - os: ubuntu-latest
            ARCH: x86_64
            DOCKER_ARCH: amd64
            DOCKERIMAGE: condaforge/linux-anvil-comp7
            MAXIFORGE_NAME: "maxiforge"
            OS_NAME: "Linux"

          - os: ubuntu-latest
            ARCH: ppc64le
            DOCKER_ARCH: ppc64le
            DOCKERIMAGE: condaforge/linux-anvil-ppc64le
            MAXIFORGE_NAME: "maxiforge"
            OS_NAME: "Linux"

          - os: ubuntu-latest
            ARCH: aarch64
            DOCKER_ARCH: arm64v8
            DOCKERIMAGE: condaforge/linux-anvil-aarch64
            MAXIFORGE_NAME: "maxiforge-pypy"
            OS_NAME: "Linux"

          - os: ubuntu-latest
            ARCH: x86_64
            DOCKER_ARCH: amd64
            DOCKERIMAGE: condaforge/linux-anvil-comp7
            MAXIFORGE_NAME: "maxiforge-pypy"
            OS_NAME: "Linux"

          - os: ubuntu-latest
            ARCH: ppc64le
            DOCKER_ARCH: ppc64le
            DOCKERIMAGE: condaforge/linux-anvil-ppc64le
            MAXIFORGE_NAME: "maxiforge-pypy"
            OS_NAME: "Linux"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Windows specific setup
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
      if: contains(matrix.OS_NAME, 'Windows')

    - name: Build and test maxiforge
      env:
        ARCH: ${{ matrix.ARCH }}
        MAXIFORGE_NAME: ${{ matrix.MAXIFORGE_NAME }}
        OS_NAME: ${{ matrix.OS_NAME }}
        DOCKERIMAGE: ${{ matrix.DOCKERIMAGE }}
        DOCKER_ARCH: ${{ matrix.DOCKER_ARCH }}
      run: |
        if [[ "$OS_NAME" == "Linux" ]]; then
          bash build_maxiforge_linux.sh;
          EXT=sh
        fi
        if [[ "$OS_NAME" == "MacOSX" ]]; then
          bash build_maxiforge_macos.sh;
          EXT=sh
        fi
        if [[ "$OS_NAME" == "Windows" ]]; then
          source /c/Miniconda3/Scripts/activate;
          source build_maxiforge_windows.sh;
          EXT=exe
        fi
      shell: bash

    - run: ls -la build/

    - name: Upload maxiforge to Github artifact
      uses: actions/upload-artifact@v2
      with:
        path: build/${{ matrix.MAXIFORGE_NAME }}-${{ matrix.OS_NAME }}-${{ matrix.ARCH }}*
        name: ${{ matrix.MAXIFORGE_NAME }}-${{ matrix.OS_NAME }}-${{ matrix.ARCH }}
