name: CI

on: push

jobs:
  build:
    name: ${{ matrix.MAXICONDA_NAME }}-${{ matrix.OS_NAME }}-${{ matrix.ARCH }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            ARCH: x86_64
            MAXICONDA_NAME: "maxiconda"
            OS_NAME: "Windows"

          - os: macos-latest
            ARCH: x86_64
            MAXICONDA_NAME: "maxiconda"
            OS_NAME: "MacOSX"

          # - os: macos-latest
          #   ARCH: arm64
          #   MAXICONDA_NAME: "maxiconda"
          #   OS_NAME: "MacOSX"

          - os: macos-latest
            ARCH: x86_64
            MAXICONDA_NAME: "maxiconda-pypy"
            OS_NAME: "MacOSX"

          # - os: macos-latest
          #   ARCH: arm64
          #   MAXICONDA_NAME: "maxiconda-pypy"
          #   OS_NAME: "MacOSX"

          - os: ubuntu-latest
            ARCH: x86_64
            DOCKER_ARCH: amd64
            DOCKERIMAGE: condaforge/linux-anvil-comp7
            MAXICONDA_NAME: "maxiconda"
            OS_NAME: "Linux"

          - os: ubuntu-latest
            ARCH: aarch64
            DOCKER_ARCH: arm64v8
            DOCKERIMAGE: condaforge/linux-anvil-aarch64
            MAXICONDA_NAME: "maxiconda"
            OS_NAME: "Linux"

          - os: ubuntu-latest
            ARCH: x86_64
            DOCKER_ARCH: amd64
            DOCKERIMAGE: condaforge/linux-anvil-comp7
            MAXICONDA_NAME: "maxiconda-pypy"
            OS_NAME: "Linux"

          - os: ubuntu-latest
            ARCH: aarch64
            DOCKER_ARCH: arm64v8
            DOCKERIMAGE: condaforge/linux-anvil-aarch64
            MAXICONDA_NAME: "maxiconda-pypy"
            OS_NAME: "Linux"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Windows-only setup
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
      if: contains(matrix.OS_NAME, 'Windows')

    - name: Build and test maxiconda
      env:
        ARCH: ${{ matrix.ARCH }}
        MAXICONDA_NAME: ${{ matrix.MAXICONDA_NAME }}
        OS_NAME: ${{ matrix.OS_NAME }}
        DOCKERIMAGE: ${{ matrix.DOCKERIMAGE }}
        DOCKER_ARCH: ${{ matrix.DOCKER_ARCH }}
      run: |
        if [[ "$OS_NAME" == "Linux" ]]; then
          bash build_maxiconda_linux.sh;
          EXT=sh
        fi
        if [[ "$OS_NAME" == "MacOSX" ]]; then
          bash build_maxiconda_macos.sh;
          EXT=sh
        fi
        if [[ "$OS_NAME" == "Windows" ]]; then
          source /c/Miniconda3/Scripts/activate;
          source build_maxiconda_windows.sh;
          EXT=exe
        fi
      shell: bash

    - name: Upload maxiconda to Github artifact
      uses: actions/upload-artifact@v2
      with:
        path: build/*
        name: ${{ matrix.MAXICONDA_NAME }}-${{ matrix.OS_NAME }}-${{ matrix.ARCH }}
